# 站點基本資訊
title: "Jimmy Hua's Notion Export"
description: "Blog powered by Not Pure Poole"
url: "https://jimmyhua123.github.io"
baseurl: "/jimmyhua_notion.github.io"   # 若你的網站路徑帶有 repo 名稱

avatar: "/avatar.jpeg"            # 若你的頭像檔案實際在 /assets/images/avatar.jpeg，請改成 /assets/images/avatar.jpeg
cover_image: "/bg.jpg"           # 若有背景圖，路徑同上
permalink: pretty
paginate: 5

# 使用 kramdown 作為 Markdown 解析器
markdown: kramdown

# kramdown 設定
kramdown:
  input: GFMKatex       # 告知 kramdown 使用自訂的 GFMKatex 解析器
  hard_wrap: false
  auto_ids: true
  math_engine: mathjax   # 保留 MathJax 做渲染
  math_engine_opts:
    # 設定數學公式的分隔符（依你希望的方式調整）
    inline_math_delimiters: ['\\(', '\\)']
    display_math_delimiters: ['$$', '$$']


# 啟用 Not Pure Poole 主題
remote_theme: vszhub/not-pure-poole

# Plugins (GitHub Pages 白名單可用的外掛)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - images

# SEO 與社群相關設定
# twitter:
#   username: "你的 Twitter 帳號"   # e.g. jimmyhua
#   card: summary
logo: "/logo.png"                # 如果有自己的 logo
social:
  name: "Jimmy Hua"
  links:
    # - "https://twitter.com/你的 Twitter 帳號"
    - "https://github.com/jimmyhua123"


# 語系
lang: "zh-TW"

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# 文章與數學式設定
future: true     # 允許顯示未來日期的文章
math: true       # 若要在文章中啟用 MathJax，可再於文章 front matter 裡指定 `math: true`

# 分頁設定
pagination:
  enabled: true
  per_page: 5
paginate_path: "/page:num/"

# 排除不需要處理的檔案或資料夾
exclude:
  - config.json
  - notion_to_markdown.py
  - test_notion_api.py
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# 文章作者資訊 (顯示於文章頁尾等處)
author:
  name: "Jimmy Hua"
  url: "https://github.com/jimmyhua123"
  email: "jimmy0624062461@gmail.com"
